### ISSUE TITLE
'pip install gogokit' not working

### ISSUE THREAD

**Issue by niksite** [viagogo/gogokit.py#1]
On install of the lib: IOError: [Errno 2] No such file or directory: 'LICENSE.txt'
Full pip.log file attached.

[pip.log.txt](https://github.com/viagogo/gogokit.py/files/47344/pip.log.txt)

**Comment by maxab** [comment]
Fixed with 0.1.3
Thanks for pointing this out

**Comment by niksite** [comment]
Now, I see the following:

```
Downloading/unpacking gogokit
  Downloading gogokit-0.1.3.zip
  Running setup.py egg_info for package gogokit
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/var/sites/cityguides/env/build/gogokit/setup.py", line 20, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/var/sites/cityguides/env/build/gogokit/setup.py", line 20, in <module>

    long_description=open('README.md').read(),

IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by maxab** [comment]
Just made another change, can you try again?

**Comment by niksite** [comment]
thanks, now pip install working well
